FROM node:20.14-slim AS builder

WORKDIR /app

RUN npm install -g bun --ignore-scripts
RUN bun --version

COPY package.json ./
COPY bun.lockb ./

RUN bun install

COPY . .

RUN bun run build

FROM node:20.14-slim AS deployer

WORKDIR /app

COPY --from=builder /app/build build/
COPY --from=builder /app/package.json .

EXPOSE 4173

ENV NODE_ENV=production

CMD [ "node", "build" ]
